% chkmlver  Check MATLAB version for EasySpin
%
%    msg = chkmlver
%
%    Returns a non-empty string in msg if the MATLAB
%    version is not suitable for running EasySpin.
%
%    Usage: warning(chkmlver), error(chkmlver)

function msg = chkmlver

minimalMATLABVersion = '9.11';  % 9.11 = R2021b
minimalMATLABVersionString = 'R2021b';
minimalOctaveVersion = '10.3.0';

if ~isOctave && verLessThan('matlab',minimalMATLABVersion)  %#ok<*VERLESSMATLAB>
  msg = sprintf([...
    '\n\n'...
    '=========================================================================\n'...
    'Easyspin: MATLAB version not supported\n'...
    '-------------------------------------------------------------------------\n'...
    'This version of EasySpin requires MATLAB %s and later.\n'...
    'Your MATLAB version %s is not supported.\n'...
    'EasySpin might still run, but there is no guarantee.\n'...
    '=========================================================================\n'],...
    minimalMATLABVersionString,version);
elseif isOctave && verLessThan('octave',minimalOctaveVersion)  %#ok<*VERLESSMATLAB>
  msg = sprintf([...
    '\n\n'...
    '=========================================================================\n'...
    'Easyspin: Octave version not supported\n'...
    '-------------------------------------------------------------------------\n'...
    'This version of EasySpin is tested on Octave %s (or later).\n'...
    'Your Octave version %s is not supported.\n'...
    'EasySpin might still run, but there is no guarantee.\n'...
    '=========================================================================\n'],...
    minimalOctaveVersion,version);
else
  msg = '';
end
